### ISSUE TITLE
Multiple students confused by whether or not learn has installed correctly

### ISSUE THREAD

**Issue by JessRudder** [learn-co-curriculum/ruby-environment-setup-summary#18]
We've had quite a few students ask if learn was installed correctly when they get the following message:

```bash
Connecting to Learn...
Authenticating...
You don't appear to be in a Learn lesson's directory. Please cd to an appropriate directory and try again.
```
The current text tells them that as long as they don't get a clang error, they're fine.  I would specifically mention the language above and tell them that means that Learn is correctly installed and that they will see how it works when they get to the "First Learn Lab" lesson in a bit.

**Comment by AnnJohn** [comment]
@aviflombaum there are a lot of issues raised around environment setup in general. Should these lessons be re-worked or will this be covered in onboarding and these labs will be removed.
