### ISSUE TITLE
Consider adding "if this failed, do X" to setup instructions

### ISSUE THREAD

**Issue by wifelette** [learn-co-curriculum/ruby-environment-setup-summary#19]
In my case, so far I've hit one main issue, which is that setup doesn't seem to have installed the `learn-co` gem. I ran `gem install learn-co` and problem solved of course, but I wonder if it might be helpful to have that course correction right there in the page, especially since in some cases it's super simple (and not getting what you expect as output can be intimidating this early on).

(I was also running the wrong version of Ruby (2.2.1), and needed to update and change my default. The page doesn't really address this, simply assumes you got 2.2.2. Unsure if this matters enough to be worth explaining as well.)

Happy to submit this particular edit (the missing gem) myself if it sounds correct. Just unsure if there's a larger plan here that left this sort of info out on purpose.

**Comment by aviflombaum** [comment]
Thanks for the tip!

The environment setup is one of the most troublesome steps we try to simplify. We plan on providing a way better debugging experience during setup very soon.
