### ISSUE TITLE
using Windows based PC not an Apple computer

### ISSUE THREAD

**Issue by CLeeson** [learn-co-curriculum/ruby-environment-setup-summary#22]
Why am I seeing everything to set things up for an Apple computer? I can not go back, and Lesson 5 is for setting up in an Apple environment.

**Comment by pletcher** [comment]
Hi @CLeeson, thanks for reporting this issue, and sorry for the confusion. I'm going to close this issue for now, as there should be separate setup instructions (in your case, for using Nitrious.io) available now.

Please feel free to reopen if you're still having trouble!
