### ISSUE TITLE
Report from student

### ISSUE THREAD

**Issue by matbalez** [learn-co-curriculum/ruby-environment-setup-summary#5]
User: mike-henrich

Batch: vfa-2015

Current Lesson: Mac OS X Environment Setup

Location: https://learn.co/tracks/vfa-new-developer-training/getting-started/overview/mac-os-x-environment-setup?track_id=7538&batch_id=104

Bug Description: Just a typo - feel free let me know if there's a better place to report this. In the Getting Started > Navigating the Command Line > Study Guide, section "Copy Copy Copy with CP", the command should read "cp apple.txt dragon_cage" (I think). Having so much fun using this!

**Comment by BenjaGross** [comment]
@matbalez this is no longer an issue with this read-me
